name: deno_redis

on: [push, pull_request]

jobs:
  build-and-deploy:
    name: ${{ matrix.kind }} ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 60
    strategy:
      matrix:
        os: [macOS-latest, windows-2019, ubuntu-16.04]
        kind: ["test", "lint"]

    steps:
      - name: Clone repository
        uses: actions/checkout@v1
